#' @title Get Laboratory Test Results (LB) domain Z-score for a given STUDYID from SQLite Database or `.xpt` Files
#'
#' @description
#' This function computes the LB Z-score for a given STUDYID using data stored in a specified database.
#' It offers various optional parameters to customize the output, such as whether to return individual scores or Z-scores by `USUBJID`.
#'
#' @param studyid Character. STUDYID number. Defaults to `NULL`.
#'    Required for SQLite databases (`use_xpt_file = FALSE`).
#'    Must be `NULL` for `.xpt` files (`use_xpt_file = TRUE`).
#' @param path_db Character. Path to the SQLite database file or a folder containing `.xpt` files. Mandatory.
#' @param fake_study Logical. Whether the study data is generated by the `SENDsanitizer` package. Defaults to `FALSE`.
#' @param use_xpt_file Logical. Whether to retrieve study data from `.xpt` files instead of the SQLite database. Defaults to `FALSE`.
#' @param master_compiledata Optional, character \cr
#'   If `master_compiledata` is not supplied (i.e., `NULL`), the function will automatically call the `get_compile_data` function to calculate it.
#' @param return_individual_scores Optional, logical \cr
#'   If TRUE, the function returns individual scores for each domain by averaging the scores of all subjects/animals (`USUBJID`) in the study. Default is `FALSE`.
#' @param return_zscore_by_USUBJID Optional, logical \cr
#'    If `TRUE`, the function returns Z-scores for each animal/subject by `USUBJID`. Default is `FALSE`.
#'
#' @return
#' A data frame containing the LB Z-scores:
#' - If `return_individual_scores = TRUE`: Returns averaged Z-scores for each  domain per `studyid`.
#' - If `return_zscore_by_USUBJID = TRUE`: Returns Z-score for each animal/subject by `USUBJID` for each domain per `studyid`.
#' - Otherwise, a summarized BW score for the specified `studyid`.
#'
#' @examples
#' \dontrun{
#' # Example usage of the function
#' get_lb_score(studyid='1234123', path_db='path/to/database.db')
#' }
#'
#' @export

get_lb_score <- function(studyid = NULL,
                         path_db,
                         fake_study= FALSE,
                         use_xpt_file = FALSE,
                         master_compiledata = NULL,
                         return_individual_scores = FALSE,
                         return_zscore_by_USUBJID = FALSE) {

  studyid <- as.character(studyid)
  path <- path_db

  # Helper function to fetch data from SQLite database
  fetch_domain_data <- function(db_connection, domain_name, studyid) {
    domain_name <- toupper(domain_name)
    query_statement <- paste0('SELECT * FROM ', domain_name, " WHERE STUDYID = :x")
    query_result <- DBI::dbGetQuery(db_connection, statement = query_statement, params = list(x = studyid))
    query_result
  }

  # GET THE REQUIRED DOMAIN DATA
  if (use_xpt_file) {
    # Read data from .xpt files
    lb <- haven::read_xpt(fs::path(path, 'lb.xpt'))
  } else {
    # Read data from .csv files
    lb <- read.csv(fs::path(path, 'lb.csv'))[,-1]
    lb[is.na(lb)] <- ''
  }

  # Print the dimension of the data frames
  print("*********************************************************************************************************")
  print("*********************************************************************************************************")
  cat("The dimension of '.......lb...data...frame.......' is:--------", dim(lb)[1], "rows and", dim(lb)[2], "columns.\n")
  print("*********************************************************************************************************")
  print("*********************************************************************************************************")




    # check the lb data frame
    organTESTCDlist <- list('LIVER' = c('SERUM | ALT',
                                        'SERUM | AST',
                                        'SERUM | ALP',
                                        'SERUM | GGT',
                                        'SERUM | BILI',
                                        'SERUM | ALB',
                                        'PLASMA | ALT',
                                        'PLASMA | AST',
                                        'PLASMA | ALP',
                                        'PLASMA | GGT',
                                        'PLASMA | BILI',
                                        'PLASMA | ALB',
                                        'WHOLE BLOOD | ALT',
                                        'WHOLE BLOOD | AST',
                                        'WHOLE BLOOD | ALP',
                                        'WHOLE BLOOD | GGT',
                                        'WHOLE BLOOD | BILI',
                                        'WHOLE BLOOD | ALB'))

    #Make LB Data Data Frame to Hold Information
    LBData <- data.frame("STUDYID" = NA,"USUBJID" = NA,"LBSPEC" = NA,"LBTESTCD" = NA,
                         "LBSTRESN" = NA, "VISITDY" = NA)

    # for (Name in unique(filtered_combined_lb$STUDYID)) {
    # Filter the data for the current STUDYID
    study_data_LB <- lb
    if (nrow(study_data_LB) == 0) {

      if (return_individual_scores) {

        master_lb_scores <- data.frame("STUDYID" = studyid, lb_score = "NA")

        return(master_lb_scores)

      } else if(return_zscore_by_USUBJID) {

        LB_zscore_by_USUBJID_HD <- data.frame("STUDYID" = studyid, "USUBJID" = NA, lb_score = "NA")

        return (LB_zscore_by_USUBJID_HD )

      } else  {

        averaged_LB_score <- data.frame("STUDYID" = studyid, lb_score = "NA")
        # Handle case when (return_individual_scores == FALSE && return_zscore_by_USUBJID == FALSE
        return(averaged_LB_score)
      }



    } else {


    # Check if LBDY column exists and process accordingly
    if ("LBDY" %in% names(study_data_LB)) {
      LBD <- study_data_LB %>%
        dplyr::filter(LBDY >= 1) %>%
        dplyr::select(STUDYID,USUBJID, LBSPEC, LBTESTCD, LBSTRESN, LBDY)
      # renaming the column
      colnames(LBD) <- c("STUDYID", "USUBJID", "LBSPEC", "LBTESTCD", "LBSTRESN", "VISITDY")

      # Convert LBCAT to LBSPEC if LBSPEC is NA
      if (all(is.na(LBD$LBSPEC))) {
        LBD$LBSPEC <- study_data_LB$LBCAT[study_data_LB$LBDY >= 1]

        if (any(c("HEMATOLOGY", "Hematology","hematology") %in% levels(LBD$LBSPEC))){
          levels(LBD$LBSPEC)[match(c("HEMATOLOGY", "Hematology","hematology"),
                                   levels(LBD$LBSPEC))] <- "WHOLE BLOOD"
        }
        if (any(c("CLINICAL CHEMISTRY","Clinical Chemistry") %in% levels(LBD$LBSPEC))){
          levels(LBD$LBSPEC)[match(c("CLINICAL CHEMISTRY","Clinical Chemistry"),
                                   levels(LBD$LBSPEC))] <- "SERUM"
        }
        if (any(c("URINALYSIS","Urinalysis") %in% levels(LBD$LBSPEC))){
          levels(LBD$LBSPEC)[match(c("URINALYSIS","Urinalysis"),
                                   levels(LBD$LBSPEC))] <- "URINE"
        }
      }
    } else {
      # If LBDY column does not exist, handle accordingly
      LBD <- study_data_LB[which(study_data_LB$VISITDY >= 1),
                           c("STUDYID","USUBJID","LBSPEC","LBTESTCD","LBSTRESN", "VISITDY")]
    }

    # Add to LBData
    LBData <- rbind(LBData, LBD)

    # Remove rows with all NAs
    LBData <- stats::na.omit(LBData)

    # Concatenate LBSPEC and LBTESTCD
    LBData$LBTESTCD <- paste(LBData$LBSPEC, LBData$LBTESTCD, sep = ' | ')

    #Remove Not Included Tests...............................................................
    # This step remove not rows matching test from ogransystem
    test_cleaned_LBData <- LBData[LBData$LBTESTCD %in% organTESTCDlist[['LIVER']],]

    # Create a new data frame with the row having the max VISITDY for each USUBJID and LBTESTCD combination
    max_visitdy_df <- test_cleaned_LBData %>%
      dplyr::group_by(USUBJID, LBTESTCD) %>%
      dplyr::filter(VISITDY == max(VISITDY, na.rm = TRUE)) %>%
      dplyr::ungroup()

  # master_compiledata <- get_compile_data(studyid, path_db,fake_study = fake_study)

    #<><><><><>... Remove TK animals and Recovery animals......<><><><><><>.
    #<><> master_compiledata is free of TK animals and Recovery animals<><><>


    if (is.null(master_compiledata)) {

      studyid <- if (use_xpt_file) NULL else studyid

      master_compiledata <- get_compile_data(studyid = studyid,
                                             path_db = path_db,
                                             fake_study = fake_study,
                                             use_xpt_file = use_xpt_file)
    }


    # # Filtering the tk animals and the recovery animals
    # # Remove the TK animals and Recovery animals

    LB_tk_recovery_filtered <- max_visitdy_df %>%
      dplyr::filter(USUBJID %in% master_compiledata$USUBJID)

    # Perform a left join to match USUBJID and get ARMCD ## 020924
    #-inner_join() used instead of left_join()#199
    LB_tk_recovery_filtered_ARMCD <- LB_tk_recovery_filtered %>%
      dplyr::inner_join(master_compiledata %>% dplyr::select(USUBJID, ARMCD), by = "USUBJID")


    # "zScore Calculation" for LB data
    # First subset the LB_tk_recovery_filtered_ARMCD data frame

    # .................Filtering data for each unique "LBTESTCD" value........

    # 1. Sub-setting for 'SERUM | ALT' data frame for "LBzScore Calculation" for...'SERUM | ALT'...........
    df_serum_alt <- LB_tk_recovery_filtered_ARMCD %>%
      dplyr::filter(LBTESTCD == 'SERUM | ALT' | LBTESTCD == 'PLASMA | ALT'| LBTESTCD == 'WHOLE BLOOD | ALT')

    # calculate the zscore of 'SERUM | ALT'
    zscore_serum_alt <- df_serum_alt %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        mean_vehicle_alt = mean(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle_alt = stats::sd(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(
        alt_zscore = (LBSTRESN - mean_vehicle_alt) / sd_vehicle_alt
      )%>%
      dplyr::mutate(alt_zscore = abs(alt_zscore))

    # averaged zscore per STUDYID for 'SERUM | ALT'
    serum_alt_final_zscore <- zscore_serum_alt %>%
      dplyr::filter(ARMCD == "HD") %>%  # Step 1: Filter for HD
      dplyr::group_by(STUDYID) %>%  # Step 2: Group by STUDYID
      dplyr::summarise(
        avg_alt_zscore = mean(alt_zscore, na.rm = TRUE),  # Step 3: Average alt_zscore
        LBTESTCD = dplyr::first(LBTESTCD)  # Include LBTESTCD in the summarized data
      ) %>% dplyr::select (STUDYID, avg_alt_zscore )%>% #select (avg_alt_zscore ) %>%
      dplyr::mutate(avg_alt_zscore = ifelse(avg_alt_zscore >= 3, 3,
                                            ifelse(avg_alt_zscore >= 2, 2,
                                                   ifelse(avg_alt_zscore >= 1, 1, 0))))
        # dplyr::mutate(avg_alt_zscore = ifelse(avg_alt_zscore == 5, 5,
        #                                   ifelse(avg_alt_zscore > 3, 3,
        #                                          ifelse(avg_alt_zscore == 3, 2,
        #                                                 ifelse(avg_alt_zscore > 0, 1, 0)))))

    # x <- ifelse(mi_CompileData2[[colName]] == 5, 5,
    #             ifelse(mi_CompileData2[[colName]] > 3, 3,
    #                    ifelse(mi_CompileData2[[colName]] == 3, 2,
    #                           ifelse(mi_CompileData2[[colName]] > 0, 1, 0))))


    # 2. Sub-setting for 'SERUM | AST' data frame for "BWzScore Calculation" for...'SERUM | AST'...........
    df_serum_ast <- LB_tk_recovery_filtered_ARMCD %>%
      dplyr::filter(LBTESTCD == 'SERUM | AST' | LBTESTCD == 'PLASMA | AST'| LBTESTCD == 'WHOLE BLOOD | AST')

    # calculate the zscore of 'SERUM | AST'
    zscore_serum_ast <- df_serum_ast %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        mean_vehicle_ast = mean(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle_ast = stats::sd(LBSTRESN[ARMCD  == "vehicle"], na.rm = TRUE)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(
        ast_zscore = (LBSTRESN - mean_vehicle_ast) / sd_vehicle_ast
      )%>%
      dplyr::mutate(ast_zscore = abs(ast_zscore))

    # averaged zscore per STUDYID for 'SERUM | AST'
    serum_ast_final_zscore <- zscore_serum_ast %>%
      dplyr::filter(ARMCD  == "HD") %>%  # Step 1: Filter for HD
      dplyr::group_by(STUDYID) %>%  # Step 2: Group by STUDYID
      dplyr::summarise(
        avg_ast_zscore = mean(ast_zscore, na.rm = TRUE),  # Step 3: Average alt_zscore
        LBTESTCD = dplyr::first(LBTESTCD)  # Include LBTESTCD in the summarized data
      )  %>% dplyr::select(STUDYID, avg_ast_zscore) %>% #select(avg_ast_zscore) %>%
      dplyr::mutate(avg_ast_zscore = ifelse(avg_ast_zscore >= 3, 3,
                                            ifelse(avg_ast_zscore >= 2, 2,
                                                   ifelse(avg_ast_zscore >= 1, 1, 0))))
      # dplyr::mutate(avg_ast_zscore = ifelse(avg_ast_zscore == 5, 5,
      #                                       ifelse(avg_ast_zscore > 3, 3,
      #                                              ifelse(avg_ast_zscore == 3, 2,
      #                                                     ifelse(avg_ast_zscore > 0, 1, 0)))))


    # 3........Sub-setting for 'SERUM | ALP' data frame for "BWzScore Calculation" for...'SERUM | ALP'...........
    df_serum_alp <- LB_tk_recovery_filtered_ARMCD %>%
      dplyr::filter(LBTESTCD == 'SERUM | ALP'| LBTESTCD == 'PLASMA | ALP'| LBTESTCD == 'WHOLE BLOOD | ALP')

    # calculate the zscore of 'SERUM | ALP'
    zscore_serum_alp <- df_serum_alp %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        mean_vehicle_alp = mean(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle_alp = stats::sd(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(
        alp_zscore = (LBSTRESN - mean_vehicle_alp) / sd_vehicle_alp
      )%>%
      dplyr::mutate(alp_zscore = abs(alp_zscore))

    # averaged zscore per STUDYID for 'SERUM | ALP'
    serum_alp_final_zscore <- zscore_serum_alp %>%
      dplyr::filter(ARMCD == "HD") %>%  # Step 1: Filter for HD
      dplyr::group_by(STUDYID) %>%  # Step 2: Group by STUDYID
      dplyr::summarise(
        avg_alp_zscore = mean(alp_zscore, na.rm = TRUE),  # Step 3: Average alt_zscore
        LBTESTCD = dplyr::first(LBTESTCD)  # Include LBTESTCD in the summarized data
      ) %>% dplyr::select (STUDYID, avg_alp_zscore) %>% #select (avg_alp_zscore) %>%
      dplyr::mutate(avg_alp_zscore = ifelse(avg_alp_zscore >= 3, 3,
                                            ifelse(avg_alp_zscore >= 2, 2,
                                                   ifelse(avg_alp_zscore >= 1, 1, 0))))
        # dplyr::mutate(avg_alp_zscore = ifelse(avg_alp_zscore == 5, 5,
        #                                       ifelse(avg_alp_zscore > 3, 3,
        #                                              ifelse(avg_alp_zscore == 3, 2,
        #                                                     ifelse(avg_alp_zscore > 0, 1, 0)))))

    # 4. Sub-setting for 'SERUM | GGT' data frame for "BWzScore Calculation" for...'SERUM | GGT'...........
    df_serum_ggt <- LB_tk_recovery_filtered_ARMCD %>%
      dplyr::filter(LBTESTCD == 'SERUM | GGT'| LBTESTCD == 'PLASMA | GGT'| LBTESTCD == 'WHOLE BLOOD | GGT')

    # calculate the zscore of 'SERUM | GGT'
    zscore_serum_ggt <- df_serum_ggt %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        mean_vehicle_ggt = mean(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle_ggt = stats::sd(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(
        ggt_zscore = (LBSTRESN - mean_vehicle_ggt) / sd_vehicle_ggt
      )%>%
      dplyr::mutate(ggt_zscore = abs(ggt_zscore))

    # averaged zscore per STUDYID for 'SERUM | GGT'
    serum_ggt_final_zscore <- zscore_serum_ggt %>%
      dplyr::filter(ARMCD == "HD") %>%  # Step 1: Filter for HD
      dplyr::group_by(STUDYID) %>%  # Step 2: Group by STUDYID
      dplyr::summarise(
        avg_ggt_zscore = mean(ggt_zscore, na.rm = TRUE),  # Step 3: Average alt_zscore
        LBTESTCD = dplyr::first(LBTESTCD)  # Include LBTESTCD in the summarized data
      ) %>% dplyr::select(STUDYID, avg_ggt_zscore) %>% #select(avg_ggt_zscore) %>%
      dplyr::mutate(avg_ggt_zscore = ifelse(avg_ggt_zscore >= 3, 3,
                                            ifelse(avg_ggt_zscore >= 2, 2,
                                                   ifelse(avg_ggt_zscore >= 1, 1, 0))))
      # dplyr::mutate(avg_ggt_zscore = ifelse(avg_ggt_zscore == 5, 5,
      #                                       ifelse(avg_ggt_zscore > 3, 3,
      #                                              ifelse(avg_ggt_zscore == 3, 2,
      #                                                     ifelse(avg_ggt_zscore > 0, 1, 0)))))

    #5.  Sub-setting for 'SERUM | BILI' data frame for "BWzScore Calculation" for...'SERUM | BILI'...........
    df_serum_bili <- LB_tk_recovery_filtered_ARMCD %>%
      dplyr::filter(LBTESTCD == 'SERUM | BILI'| LBTESTCD == 'PLASMA | BILI'| LBTESTCD == 'WHOLE BLOOD | BILI')

    # calculate the zscore of 'SERUM | BILI'
    zscore_serum_bili <- df_serum_bili %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        mean_vehicle_bili = mean(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle_bili = stats::sd(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(
        bili_zscore = (LBSTRESN - mean_vehicle_bili) / sd_vehicle_bili
      )%>%
      dplyr::mutate(bili_zscore = abs(bili_zscore))

    # averaged zscore per STUDYID for 'SERUM | BILI'
    serum_bili_final_zscore <- zscore_serum_bili %>%
      dplyr::filter(ARMCD == "HD") %>%  # Step 1: Filter for HD
      dplyr::group_by(STUDYID) %>%  # Step 2: Group by STUDYID
      dplyr::summarise(
        avg_bili_zscore = mean(bili_zscore, na.rm = TRUE),  # Step 3: Average alt_zscore
        LBTESTCD = dplyr::first(LBTESTCD)  # Include LBTESTCD in the summarized data
      )  %>% dplyr::select(STUDYID, avg_bili_zscore) %>% #select(avg_bili_zscore) %>%
      dplyr::mutate(avg_bili_zscore = ifelse(avg_bili_zscore >= 3, 3,
                                             ifelse(avg_bili_zscore >= 2, 2,
                                                    ifelse(avg_bili_zscore >= 1, 1, 0))))
        # dplyr::mutate(avg_bili_zscore = ifelse(avg_bili_zscore == 5, 5,
        #                                        ifelse(avg_bili_zscore > 3, 3,
        #                                               ifelse(avg_bili_zscore == 3, 2,
        #                                                      ifelse(avg_bili_zscore > 0, 1, 0)))))

    # 6. Sub-setting for 'SERUM | ALB' data frame for "BWzScore Calculation" for...'SERUM | ALB'...........
    df_serum_alb <- LB_tk_recovery_filtered_ARMCD %>%
      dplyr::filter(LBTESTCD == 'SERUM | ALB'| LBTESTCD == 'PLASMA | ALB'| LBTESTCD == 'WHOLE BLOOD | ALB')

    # calculte the zscore of 'SERUM | ALB'
    zscore_serum_alb <- df_serum_alb %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        mean_vehicle_alb = mean(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle_alb = stats::sd(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(
        alb_zscore = (LBSTRESN - mean_vehicle_alb) / sd_vehicle_alb
      )%>%
      dplyr::mutate(alb_zscore = abs(alb_zscore))

    # averaged zscore per STUDYID for 'SERUM | ALB'
    serum_alb_final_zscore <- zscore_serum_alb %>%
      dplyr::filter(ARMCD == "HD") %>%  # Step 1: Filter for HD
      dplyr::group_by(STUDYID) %>%  # Step 2: Group by STUDYID
      dplyr::summarise(
        avg_alb_zscore = mean(alb_zscore, na.rm = TRUE),  # Step 3: Average alt_zscore
        LBTESTCD = dplyr::first(LBTESTCD)  # Include LBTESTCD in the summarized data
      ) %>% dplyr::select(STUDYID, avg_alb_zscore) %>% #select(avg_alb_zscore) %>%
      dplyr::mutate(avg_alb_zscore = ifelse(avg_alb_zscore >= 3, 3,
                                            ifelse(avg_alb_zscore >= 2, 2,
                                                   ifelse(avg_alb_zscore >= 1, 1, 0))))
      # dplyr::mutate(avg_alb_zscore = ifelse(avg_alb_zscore == 5, 5,
      #                                       ifelse(avg_alb_zscore > 3, 3,
      #                                              ifelse(avg_alb_zscore == 3, 2,
      #                                                     ifelse(avg_alb_zscore > 0, 1, 0)))))

    # print(serum_alb_final_zscore)
    # print(serum_ast_final_zscore)
    # print(serum_alp_final_zscore)
    # print(serum_alt_final_zscore)
    # print(serum_bili_final_zscore)
    # print(serum_ggt_final_zscore)


    # Merging----------LB----zscores------------values-------------------
    LB_zscore_merged_df <- serum_alb_final_zscore %>%
      dplyr::full_join(serum_ast_final_zscore, by = "STUDYID") %>%
      dplyr::full_join(serum_alp_final_zscore, by = "STUDYID") %>%
      dplyr::full_join(serum_alt_final_zscore, by = "STUDYID") %>%
      dplyr::full_join(serum_bili_final_zscore, by = "STUDYID") %>%
      dplyr::full_join(serum_ggt_final_zscore, by = "STUDYID")


    # Replace Inf, -Inf, and NaN with NA in the selected columns
    selected_cols <- c("avg_alb_zscore", "avg_ast_zscore", "avg_alp_zscore",
                       "avg_alt_zscore", "avg_bili_zscore", "avg_ggt_zscore")

    LB_zscore_merged_df[selected_cols] <- lapply(LB_zscore_merged_df[selected_cols],
                                             function(x) replace(x, is.infinite(x) | is.nan(x), NA))

    # Enforce mutual exclusivity: If both are TRUE, throw an error or handle it
    if (return_individual_scores && return_zscore_by_USUBJID) {
      stop("Error: Both 'return_individual_scores' and 'return_zscore_by_USUBJID' cannot be TRUE at the same time.")
    }

    if (return_individual_scores) {

      # Master LB list
      master_LB_list <- data.frame(STUDYID = NA, avg_alb_zscore = NA, avg_ast_zscore = NA, avg_alp_zscore = NA,
                                   avg_alt_zscore = NA, avg_bili_zscore = NA, avg_ggt_zscore = NA)

      # Add LB_zscore_merged_df to master dataframe
      master_LB_list <- dplyr::bind_rows(master_LB_list, LB_zscore_merged_df)

      master_lb_scores <- master_LB_list #%>% master_lb_scores[-1,]
      master_lb_scores   <- master_lb_scores[-1,] # remove the first column


    } else if (return_zscore_by_USUBJID) {


       # calculate the zscore for all the uSUBJID
      # 1. Sub-setting for 'SERUM | ALT' data frame for "LBzScore Calculation"
      df_lb_for_zscore <- LB_tk_recovery_filtered_ARMCD

      # calculate the zscore
      zscore_lb <- df_lb_for_zscore %>%
        dplyr::group_by(STUDYID) %>%
        dplyr::mutate(
          mean_vehicle = mean(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE),
          sd_vehicle = stats::sd(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE)) %>%
        dplyr::ungroup() %>%
        dplyr::mutate(
          LB_zscore = (LBSTRESN - mean_vehicle) / sd_vehicle) #%>%
       # dplyr::mutate(LB_zscore = abs(LB_zscore))

        LB_zscore_by_USUBJID_HD <- zscore_lb %>%
        dplyr::filter(ARMCD == "HD") %>%  # Step 1: Filter for HD
        #dplyr::group_by(STUDYID) %>%  # Step 2: Group by STUDYID
        dplyr::mutate(LB_zscore = replace(LB_zscore,
                                        is.infinite(LB_zscore), NA)) %>%
        #dplyr::ungroup() %>%
        dplyr::mutate(LB_zscore = abs(LB_zscore))  %>%
        dplyr::select(STUDYID, USUBJID, LB_zscore) %>%
        dplyr::mutate(LB_zscore = ifelse(LB_zscore >= 3, 3,
                                                ifelse(LB_zscore >= 2, 2,
                                                       ifelse(LB_zscore >= 1, 1, 0))))
        # dplyr::mutate(LB_zscore = ifelse(LB_zscore == 5, 5,
        #                                  ifelse(LB_zscore > 3, 3,
        #                                         ifelse(LB_zscore == 3, 2,
        #                                                ifelse(LB_zscore > 0, 1, 0)))))

        # Finally, convert to a regular data frame to ensure no grouping attributes remain
        LB_zscore_by_USUBJID_HD <- as.data.frame(LB_zscore_by_USUBJID_HD)

    } else  {

      # Handle case when (return_individual_scores == FALSE && return_zscore_by_USUBJID == FALSE
      # Calculate the average for each row, ignoring NA values
      LB_zscore_merged_df$avg_all_LB_zscores <- rowMeans(LB_zscore_merged_df[selected_cols], na.rm = TRUE)

      # select the specific columns for calculation
      LB_all_liver_zscore_averaged <- LB_zscore_merged_df %>% dplyr::select (STUDYID, avg_all_LB_zscores)

      # Assigning the new variables
      LB_final_score <- LB_all_liver_zscore_averaged

      # Create "LB_df" for FOUR_Liver_Score
      averaged_LB_score <- LB_final_score %>% dplyr::rename(LB_score_avg = avg_all_LB_zscores)

      averaged_LB_score <- as.data.frame(averaged_LB_score)
    }


  if (return_individual_scores) {

  return(master_lb_scores)

  } else if(return_zscore_by_USUBJID) {

     return (LB_zscore_by_USUBJID_HD )

 } else  {
   # Handle case when (return_individual_scores == FALSE && return_zscore_by_USUBJID == FALSE
   return(averaged_LB_score)
  }

 }

}
