#' @title Get SETCD of treatment group  for a given STUDYID from SQLite Database or `.xpt` Files
#'
#' @description
#' This function retrieve the treatment_group (SETCD) a given STUDYID using data stored in a specified database.
#'
#' @param studyid Character. STUDYID number. Defaults to `NULL`.
#'    Required for SQLite databases (`use_xpt_file = FALSE`).
#'    Must be `NULL` for `.xpt` files (`use_xpt_file = TRUE`).
#' @param path_db Character. Path to the SQLite database file or a folder containing `.xpt` files. Mandatory.
#' @param fake_study Logical. Whether the study data is generated by the `SENDsanitizer` package. Defaults to `FALSE`.
#' @param use_xpt_file Logical. Whether to retrieve study data from `.xpt` files instead of the SQLite database. Defaults to `FALSE`.
#'
#' @return a data frame
#' @examples
#'
#' \dontrun{
#' # Example usage of get_mi_score
#' get_mi_score(studyid = '1234123', path_db = 'path/to/database.db')
#' }
#'
#' @export


get_treatment_group_amin <- function(studyid = NULL,
                                path_db,
                                fake_study=FALSE,
                                use_xpt_file = FALSE) {

  list_return <- list() # Initialize the result list
  four <- c()  # To store studies with exactly 4 treatment groups
  study <- studyid
  studyid <- as.character(studyid)
  path <- path_db

  # Helper function to fetch data from SQLite database
  fetch_domain_data <- function(db_connection, domain_name, studyid) {
    domain_name <- toupper(domain_name)
    query_statement <- paste0('SELECT * FROM ', domain_name, " WHERE STUDYID = :x")
    query_result <- DBI::dbGetQuery(db_connection, statement = query_statement, params = list(x = studyid))
    query_result
  }

  get_input_filename <- function(file_path, pattern) {
    input_filename <- list.files(file_path, pattern = pattern, ignore.case = TRUE)[1]
    input_filename
  }

  get_xpt_data <- function(xpt_path, pattern) {
    xpt_filename <- get_input_filename(xpt_path, pattern)
    xpt_df <- haven::read_xpt(fs::path(xpt_path, xpt_filename))
    xpt_df
  }

  get_csv_data <- function(csv_path, pattern) {
    csv_filename <- get_input_filename(csv_path, pattern)
    csv_df <- read.csv(fs::path(csv_path, csv_filename))
    empty_name_cols <- which(colnames(csv_df) == "X")
    if (length(empty_name_cols) > 0) {
      csv_df <- csv_df[, -empty_name_cols]
    } else {
      csv_df <- csv_df # No empty named columns to remove
    }
    csv_df[is.na(csv_df)] <- ''
    csv_df <- mutate(csv_df, STUDYID = as.character(STUDYID))
    csv_df
  }

  # GET THE REQUIRED DOMAIN DATA
  if (use_xpt_file) {
    # Read data from .xpt files
    dm <- get_xpt_data(path,'dm\\.xpt')
    tx <- get_xpt_data(path,'tx\\.xpt')
    ts <- get_xpt_data(path,'ts\\.xpt')
    ds <- get_xpt_data(path,'ds\\.xpt')
    pc <- get_xpt_data(path,'pc\\.xpt')

  } else {
    # Read data from .csv files
    dm <- get_csv_data(path,'dm\\.csv')
    tx <- get_csv_data(path,'tx\\.csv')
    ts <- get_csv_data(path,'ts\\.csv')
    ds <- get_csv_data(path,'ds\\.csv')
    pc <- get_csv_data(path,'pc\\.csv')
  }

  # Identify unique treatment groups (SETCD) from DM
  # and study species from ts
  number_of_setcd <- unique(dm[['SETCD']])
  print(number_of_setcd)

  # get the species from the tsparmcd
  st_species <- ts[ts$TSPARMCD=='SPECIES',"TSVAL"]

   #recovery_group <- c()
  recovery_group <- c() # Recovery groups

  not_RAT_recovery_group <- c()

  #treatment_group<- c()
  treatment_group <- c() # Treatment groups

  not_RAT_treatment_group <- c()

  Dose_Level_df <- data.frame(STUDYID = character(),
                              Dose_Level = character(),
                              Dose_Units = character(),
                              Treatment_SETCD = character())#,
  #stringsAsFactors = FALSE))

  if(length(st_species)!= 0) {

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # if species is 'RAT' , get the tk and non tk group
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Identify recovery and treatment groups in non-TK groups
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    if(st_species %in% c("RAT","MOUSE")) {

      ## filter dm sujid by the temp_df for getting the setcd
      setcd_dm_tk_less <- dm[dm$USUBJID %in% pc$USUBJID, c ("STUDYID", "USUBJID", "SETCD")]
      tk_group <- unique(setcd_dm_tk_less$SETCD)

      not_tk_group <- number_of_setcd[which(!number_of_setcd %in% tk_group)]


      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Identify recovery and treatment groups in "non-TK groups"
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      if(length(not_tk_group) > 0) {

        for (setcd in 1:length(not_tk_group)){

          set_cd <- not_tk_group[setcd]
          #subjid <- unique(dm[SETCD==set_cd, USUBJID])
          subjid <- unique(dm[dm$SETCD==set_cd, c("USUBJID")])
          #dsdecod <- tolower(unique(ds[USUBJID %in% subjid, DSDECOD]))
          dsdecod <- tolower(unique(ds[ds$USUBJID %in% subjid, "DSDECOD"])) # "ds" does not have SETCT, do had to use USUBJID matching from "dm"

          # Group assignments
          if(tolower("RECOVERY SACRIFICE") %in% dsdecod) {

            recovery_group <- c(recovery_group, set_cd)

          } else if (any(tolower(dsdecod) %in% c( "terminal sacrifice",
                                          "moribund sacrifice",
                                          "removed from study alive",
                                          "non-moribund sacrifice" ))) {
            treatment_group <- c(treatment_group, set_cd)
             }


           }

      }

      print(recovery_group)
      print(treatment_group)
       #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # get dose information for the treatment group
      # Iterate over each treatment group to extract dose information
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      for (trtm_setcd in treatment_group) {

        # Filter `tx` table for the current SETCD
        tx_trtm_setcd <- tx [tx$SETCD == trtm_setcd, ]

        # Extract dose level and dose units
        dose_level <- tx_trtm_setcd[tx_trtm_setcd$TXPARMCD == "TRTDOS", "TXVAL"]
        dose_units <- tx_trtm_setcd[tx_trtm_setcd$TXPARMCD == "TRTDOSU", "TXVAL"]

        # Get the unique treatment SETCD for the current group
        treatment_setcd <- unique(tx_trtm_setcd$SETCD)

        # Create a data frame for the current treatment group
        dose_level_df <- data.frame(STUDYID = unique(tx$STUDYID),
                                    Dose_Level = dose_level,
                                    Dose_Units =  dose_units ,
                                    Treatment_SETCD = treatment_setcd) #,
        #stringsAsFactors = FALSE)

        # Append the current data to the main data frame
        Dose_Level_df <- rbind(Dose_Level_df, dose_level_df)

      }

       } else {

      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # if species not RAT , get the tk and non tk group
      # Non-RAT species does not have tk animals ?????????????????????????????
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Identify recovery and treatment groups in non-TK groups
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      not_RAT_not_tk <- number_of_setcd

      for (i in 1:length(not_RAT_not_tk)){
        not_RAT_set_cd <- not_RAT_not_tk[i]

        #subjid <- unique(dm[SETCD==set_cd, USUBJID])
        #not_RAT_subjid <- unique(dm[dm$SETCD==set_cd, "USUBJID"])

        # Extract unique subjects and DSDECOD values
        not_RAT_subjid <- unique(dm[dm$SETCD==not_RAT_set_cd, "USUBJID"])
        #dsdecod <- tolower(unique(ds[USUBJID %in% subjid, DSDECOD]))
        not_RAT_dsdecod <- tolower(unique(ds[ds$USUBJID %in% not_RAT_subjid, "DSDECOD"]))

        # Group assignments
        if(tolower("RECOVERY SACRIFICE") %in% not_RAT_dsdecod) {
          ## print(paste0(set_cd, ' : in recovery'))
          # get the recovery group

          not_RAT_recovery_group <- c(not_RAT_recovery_group, not_RAT_set_cd)
          print(recovery_group)

        } else if (any(tolower(not_RAT_dsdecod) %in% c("terminal sacrifice",
                                                'moribund sacrifice',
                                                'removed from study alive',
                                                'removed from study alive'))){
          # get the treatment group
          not_RAT_treatment_group <- c(not_RAT_treatment_group, not_RAT_set_cd)
        }
      }
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


      print( not_RAT_recovery_group)
      print( not_RAT_treatment_group)

      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # get dose information for the treatment group
      # Iterate over each treatment group to extract dose information
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      for (not_RAT_trtm_setcd in not_RAT_treatment_group) {

        # Filter `tx` table for the current SETCD
        not_RAT_tx_trtm_setcd <- tx [tx$SETCD == not_RAT_trtm_setcd, ]

        # Extract dose level and dose units
        not_RAT_dose_level <- not_RAT_tx_trtm_setcd[not_RAT_tx_trtm_setcd$TXPARMCD == "TRTDOS", "TXVAL"]
        not_RAT_dose_units <- not_RAT_tx_trtm_setcd[not_RAT_tx_trtm_setcd$TXPARMCD == "TRTDOSU", "TXVAL"]

        # Get the unique treatment SETCD for the current group
        not_RAT_treatment_setcd <- unique(not_RAT_tx_trtm_setcd$SETCD)

        # Create a data frame for the current treatment group
        not_RAT_dose_level_df <- data.frame(STUDYID = unique(tx$STUDYID),
                                    Dose_Level = not_RAT_dose_level,
                                    Dose_Units =  not_RAT_dose_units ,
                                    Treatment_SETCD = not_RAT_treatment_setcd) #,
        #stringsAsFactors = FALSE)

        # Append the current data to the main data frame
        Dose_Level_df <- rbind(Dose_Level_df, not_RAT_dose_level_df)

        #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        # Convert the unit into a harmonized unit
        #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



      }

    #}

   }

  } else {
      # If species is = zero
      # create an empty data frame

    recovery_group <- c()
    treatment_group <- c()

  }

  if (st_species == "RAT") {
  # return(list(Dose_Level_df = Dose_Level_df,
  #             recovery_group_setcd = recovery_group,
  #             treatment_group_setcd =treatment_group))
    return(Dose_Level_df)
  } else {
    # return(list(Dose_Level_df = Dose_Level_df,
    #             recovery_group_setcd = not_RAT_recovery_group,
    #             treatment_group_setcd = not_RAT_treatment_group))
    return(Dose_Level_df)

  }
}





