#' @title Calculate Liver-to-Body-Weight ratio Z-Scores for each animal in a given STUDYID from SQLite Database or `.xpt` Files
#'
#' @description
#' This function computes liver-to-body-weight ratio  (livertoBW) of each animal and their corresponding z-scores from study data.
#' It supports retrieving data from SQLite databases or `.xpt` files and provides flexible options for output formats.
#'
#' #' @param studyid Character. STUDYID number. Defaults to `NULL`.
#'    Required for SQLite databases (`use_xpt_file = FALSE`).
#'    Must be `NULL` for `.xpt` files (`use_xpt_file = TRUE`).
#' @param path_db Character. Path to the SQLite database file or a folder containing `.xpt` files. Mandatory.
#' @param fake_study Logical. Whether the study data is generated by the `SENDsanitizer` package. Defaults to `FALSE`.
#' @param use_xpt_file Logical. Whether to retrieve study data from `.xpt` files instead of the SQLite database. Defaults to `FALSE`.
#' @param master_compiledata Optional, character \cr
#'   If `master_compiledata` is not supplied (i.e., `NULL`), the function will automatically call the `get_compile_data` function to calculate it.
#' @param bwzscore_BW Optional, data.frame. \cr
#'   if `bwzscore_BW` is not supplied (i.e., `NULL`), the function will automatically call the `get_bw_score` function to calculate it.
#' @param return_individual_scores Optional, logical \cr
#'   If TRUE, the function returns individual scores for each domain by averaging the scores of all subjects/animals (`USUBJID`) in the study. Default is `FALSE`.
#' @param return_zscore_by_USUBJID Optional, logical \cr
#'    If `TRUE`, the function returns Z-scores for each animal/subject by `USUBJID`. Default is `FALSE`.
#'
#' @return
#' A data frame containing liver-to-body-weight ratio z-scores:
#' - If `return_individual_scores = TRUE`: Returns averaged Z-scores for each  domain per `studyid`.
#' - If `return_zscore_by_USUBJID = TRUE`: Returns Z-score for each animal/subject by `USUBJID` for each domain per `studyid`.
#' - Otherwise, a summarized BW score for the specified `studyid`.
#'
#' @examples
#' \dontrun{
#' # Example 1: Default averaged scores
#' result <- get_livertobw_score(
#'   studyid = '1234123',
#'   path_db = 'path/to/database.db'
#' )
#' head(result)
#'
#' # Example 2: Individual scores by study
#' result <- get_livertobw_score(
#'   studyid = '1234123',
#'   path_db = 'path/to/database.db',
#'   return_individual_scores = TRUE
#' )
#' head(result)
#'
#' # Example 3: Z-scores by USUBJID
#' result <- get_livertobw_score(
#'   studyid = '1234123',
#'   path_db = 'path/to/database.db',
#'   return_zscore_by_USUBJID = TRUE
#' )
#' head(result)
#' }
#'
#' @export



get_livertobw_score <- function (studyid = NULL,
                                  path_db,
                                  fake_study = FALSE,
                                  use_xpt_file = FALSE,
                                  master_compiledata = NULL,
                                  bwzscore_BW = NULL,
                                  return_individual_scores = FALSE,
                                  return_zscore_by_USUBJID = FALSE){


  studyid <- as.character(studyid)
  path <- path_db


  # Helper function to fetch data from SQLite database
  fetch_domain_data <- function(db_connection, domain_name, studyid) {
    domain_name <- toupper(domain_name)
    query_statement <- paste0('SELECT * FROM ', domain_name, " WHERE STUDYID = :x")
    query_result <- DBI::dbGetQuery(db_connection, statement = query_statement, params = list(x = studyid))
    query_result
  }

  get_input_filename <- function(file_path, pattern) {
    input_filename <- list.files(file_path, pattern = pattern, ignore.case = TRUE)[1]
    input_filename
  }

  get_xpt_data <- function(xpt_path, pattern) {
    xpt_filename <- get_input_filename(xpt_path, pattern)
    xpt_df <- haven::read_xpt(fs::path(xpt_path, xpt_filename))
    xpt_df
  }

  get_csv_data <- function(csv_path, pattern) {
    csv_filename <- get_input_filename(csv_path, pattern)
    csv_df <- read.csv(fs::path(csv_path, csv_filename))
    empty_name_cols <- which(colnames(csv_df) == "X")
    if (length(empty_name_cols) > 0) {
      csv_df <- csv_df[, -empty_name_cols]
    } else {
      csv_df <- csv_df # No empty named columns to remove
    }
    csv_df[is.na(csv_df)] <- ''
    csv_df <- mutate(csv_df, STUDYID = as.character(STUDYID))
    csv_df
  }


  if (use_xpt_file) {
    # Read data from .xpt files
    om <- get_xpt_data(path,'om\\.xpt')
  } else {
    # Read data from .xpt files
    om <- get_csv_data(path, 'om\\.csv')
    om <- mutate(om, OMSTRESN = as.numeric(OMSTRESN))
  }

  # Print the dimension of the data frames
  print("*********************************************************************************************************")
  print("*********************************************************************************************************")
  cat("The dimension of '.......om...data...frame.......' is:--------", dim(om)[1], "rows and", dim(om)[2], "columns.\n")
  print("*********************************************************************************************************")
  print("*********************************************************************************************************")



    #  ..............get THE COMPILE DATA IF NOT PRESENT...............
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #<><><><><<><><>... Remove TK animals and Recovery animals........
    #..................................................................

  if (is.null(master_compiledata)) {
    studyid <- if (use_xpt_file) NULL else studyid
    master_compiledata <- get_compile_data(studyid = studyid,
                                           path_db = path_db,
                                           fake_study = fake_study,
                                           use_xpt_file = use_xpt_file)
  }


   # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   # ~~~~~~~~~~~~~~~~~~~~~~~~~Check-if-bwzscore_BW-is-NUL~~~~~~~~~~~~~~~~~~~~
   # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Check if bwzscore_BW is NULL
  if (is.null(bwzscore_BW)) {

    studyid <- if (use_xpt_file) NULL else studyid

    bwzscore_BW <-  get_bw_score(studyid = studyid ,
                                  path_db = path_db,
                                  fake_study = fake_study,
                                  use_xpt_file = use_xpt_file,
                                  master_compiledata = master_compiledata,
                                  return_individual_scores = TRUE,
                                  return_zscore_by_USUBJID = FALSE)
  }

  # Initialize data frames to store the OrganWeights_Liver data
  OrganWeights_Liver <- data.frame(USUBJID = character(0), OMSPEC = character(0), OMSTRESN = numeric(0), OMTEST = character(0))

  # Extract data for the current STUDYID
  StudyData_current_liver <- om

  # Pull index of the LIVER data
  Studyidx_liver <- which(stringr::str_detect(StudyData_current_liver$OMSPEC, "LIVER"))

  # Pull relevant OM Data for LIVER
  OMD_liver <- StudyData_current_liver[Studyidx_liver, c("USUBJID", "OMSPEC", "OMSTRESN", "OMTEST")]

  # Append to the OrganWeights_Liver  data frame
  OrganWeights_Liver <- rbind(OrganWeights_Liver, OMD_liver)

  # Filter the OrganWeights_Liver data frame
  OrganWeights_Liver_Weight <- OrganWeights_Liver %>%
    dplyr::filter(OMTEST == "Weight")

  # Filter the OrganWeights_Liver_Weight data frame and select specific columns ("USUBJID", "OMSTRESN")
  OrganWeights_Liver_Weight_Selected_Col <- OrganWeights_Liver_Weight %>%
    dplyr::filter(OMTEST == "Weight") %>%
    dplyr::select(USUBJID, OMSTRESN)


  # Filtering the tk animals and the recovery animals
  OrganWeights_Liver_filtered <- OrganWeights_Liver_Weight_Selected_Col %>%
    dplyr::filter(USUBJID %in% master_compiledata$USUBJID)

  # Perform a left join to match USUBJID and get ARMCD
  OrganWeights_Liver_with_ARMCD <- OrganWeights_Liver_filtered %>%
    dplyr::left_join(master_compiledata %>%
                       dplyr::select(STUDYID, USUBJID, ARMCD), by = "USUBJID")


  # Add "BodyWeight" data to the "OrganWeights_Liver_with_ARMCD" data frame
  OrganWeights_Liver_to_BWeight <- OrganWeights_Liver_with_ARMCD %>%
    dplyr::left_join(bwzscore_BW %>%
    dplyr::select(USUBJID, finalbodyweight), by = "USUBJID") %>%
    dplyr::mutate(liverToBW = OMSTRESN / finalbodyweight)

  # "liver_organ to BodyWeight" zscore calcualtion............................
  # Create the "LiverZSCORE" column ..........................................
  liver_zscore_df <- OrganWeights_Liver_to_BWeight %>%
    dplyr::group_by(STUDYID) %>%
    # Replace Inf and -Inf with NA in liverToBW
    dplyr::mutate(liverToBW = replace(liverToBW, is.infinite(liverToBW), NA)) %>%
    # Calculate mean and standard deviation for "vehicle" ARMCD
    dplyr::mutate(
      mean_vehicle_liverToBW = mean(liverToBW[ARMCD == "vehicle"], na.rm = TRUE),
      sd_vehicle_liverToBW = sd(liverToBW[ARMCD == "vehicle"], na.rm = TRUE)
    ) %>%
    dplyr::ungroup() %>%

    # Calculate z-score
    dplyr::mutate(
      liverToBW_zscore = (liverToBW - mean_vehicle_liverToBW) / sd_vehicle_liverToBW
    ) %>%
    # Optionally remove the mean_vehicle and sd_vehicle columns
    dplyr::select(-mean_vehicle_liverToBW, -sd_vehicle_liverToBW) %>%
    dplyr::select(STUDYID, USUBJID,liverToBW_zscore, ARMCD) %>%
    # Convert z-score to its absolute value
    dplyr::mutate(liverToBW_zscore = abs(liverToBW_zscore))

  # Filter and select specific columns
  HD_liver_zscore <- liver_zscore_df %>%
    dplyr::filter(ARMCD == "HD") %>%
    dplyr::select(STUDYID, USUBJID,  ARMCD, liverToBW_zscore)


  # Enforce mutual exclusivity: If both are TRUE, throw an error or handle it
  if (return_individual_scores && return_zscore_by_USUBJID) {
    stop("Error: Both 'return_individual_scores' and 'return_zscore_by_USUBJID' cannot be TRUE at the same time.")
  }

  if (return_individual_scores) {
      HD_liver_zscore_df <- HD_liver_zscore %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(liverToBW_zscore = replace(liverToBW_zscore,
                                               is.infinite(liverToBW_zscore), NA)) %>%
      dplyr::summarize(avg_liverToBW_zscore = mean(liverToBW_zscore, na.rm = TRUE))%>%
      dplyr::mutate(avg_liverToBW_zscore = abs(avg_liverToBW_zscore))  %>%
      dplyr::select(STUDYID, avg_liverToBW_zscore) %>%
      dplyr::mutate(avg_liverToBW_zscore = ifelse(avg_liverToBW_zscore >= 3, 3,
                                                  ifelse(avg_liverToBW_zscore >= 2, 2,
                                                         ifelse(avg_liverToBW_zscore >= 1, 1, 0))))
      # dplyr::mutate(avg_liverToBW_zscore = ifelse(avg_liverToBW_zscore == 5, 5,
      #                                             ifelse(avg_liverToBW_zscore > 3, 3,
      #                                                    ifelse(avg_liverToBW_zscore == 3, 2,
      #                                                           ifelse(avg_liverToBW_zscore > 0, 1, 0)))))
      # x <- ifelse(mi_CompileData2[[colName]] == 5, 5,
      #             ifelse(mi_CompileData2[[colName]] > 3, 3,
      #                    ifelse(mi_CompileData2[[colName]] == 3, 2,
      #                           ifelse(mi_CompileData2[[colName]] > 0, 1, 0))))

  } else if (return_zscore_by_USUBJID ) {

    # Create final_liverToBW_df for the current STUDYID by USUBJID.......................
      liverTOBW_zscore_by_USUBJID_HD <- HD_liver_zscore %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(liverToBW_zscore = replace(liverToBW_zscore,
                                               is.infinite(liverToBW_zscore), NA)) %>%
      dplyr::mutate(liverToBW_zscore = abs(liverToBW_zscore))  %>%
      dplyr::select(STUDYID, USUBJID,liverToBW_zscore) %>%
      dplyr::mutate(liverToBW_zscore = ifelse(liverToBW_zscore >= 3, 3,
                                                  ifelse(liverToBW_zscore >= 2, 2,
                                                         ifelse(liverToBW_zscore >= 1, 1, 0))))
      # dplyr::mutate(liverToBW_zscore = ifelse(liverToBW_zscore == 5, 5,
      #                                         ifelse(liverToBW_zscore > 3, 3,
      #                                                ifelse(liverToBW_zscore == 3, 2,
      #                                                       ifelse(liverToBW_zscore > 0, 1, 0)))))

  } else {
    # Create final_liverToBW_df for the current STUDYID by averaging.......................
      averaged_liverToBW_df  <- HD_liver_zscore %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(liverToBW_zscore = replace(liverToBW_zscore,
                                               is.infinite(liverToBW_zscore), NA)) %>%
      dplyr::summarize(avg_liverToBW_zscore = mean(liverToBW_zscore, na.rm = TRUE))%>%
      dplyr::mutate(avg_liverToBW_zscore = abs(avg_liverToBW_zscore))  %>%
      dplyr::select(STUDYID, avg_liverToBW_zscore) %>%
      dplyr::mutate(avg_liverToBW_zscore = ifelse(avg_liverToBW_zscore >= 3, 3,
                                                  ifelse(avg_liverToBW_zscore >= 2, 2,
                                                         ifelse(avg_liverToBW_zscore >= 1, 1, 0))))
      # dplyr::mutate(avg_liverToBW_zscore = ifelse(avg_liverToBW_zscore == 5, 5,
      #                                             ifelse(avg_liverToBW_zscore > 3, 3,
      #                                                    ifelse(avg_liverToBW_zscore == 3, 2,
      #                                                           ifelse(avg_liverToBW_zscore > 0, 1, 0)))))

  }

  # Return based on return_individual_scores
  if (return_individual_scores) {
    return(HD_liver_zscore_df)

  } else if (return_zscore_by_USUBJID ) {

    return(liverTOBW_zscore_by_USUBJID_HD)

 } else {
    return(averaged_liverToBW_df)
  }

}
